webhook_url: https://discord.com/api/webhooks/0/0
online_msg: The Minecraft Server is now <:online:956828637196345344> **Online**, you can join on 1.18.2 with the IP `product-dead.craft.playit.gg`.
offline_msg: The Minecraft Server is now <:offline:956829544281669715> **Offline**, see you later!